### ISSUE TITLE
Android onPushOpen crash the app

### ISSUE THREAD

**Issue by davideagostini** [ropilz/phonegap-parse-plugin#4]
After clicked on notification the app crash and obtain this error.
The same mistake is made in certain circumstances when open the app.

``` java
java.lang.IllegalStateException: ParsePlugins is already initialized
            at com.parse.ParsePlugins.set(ParsePlugins.java:35)
            at com.parse.ParsePlugins$Android.initialize(ParsePlugins.java:149)
            at com.parse.Parse.initialize(Parse.java:189)
            at com.medlei.ParsePlugin$2.run(ParsePlugin.java:117)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by goneale** [comment]
Same issue here :( I believe we need to rectify using this answer http://stackoverflow.com/a/32615996/41211

**Comment by Stiveknx** [comment]
You're runing `parsePlugin.initialize` on device ready?
If so, don't do it or, check if you already called the initialize event.

something like:

```
if(!window.parseLoaded){
            parsePlugin.initialize(xx, xx, function(){
                 window.parseLoaded = true;
            })
        }
```

**Comment by vahidreza** [comment]
@davideagostini @goneale 
hey guys
I just thought it might be necessary that I share my own experience regarding this plugin and the last spot I reached after so many try and errors with you.
this plugin is based on good guy's efforts like @ropilz . BUT it lacks so many features to be called a reliable plugin that has good feature set. actually you won't find a reliable one written for parse which works smoothly on both iOS and android supporting previous versions of phonegap (like mine which is 3.7)
I've tested it in one of my production apps after overcoming so many force close errors based on @ropilz  guidance (tnx by the way :)  ). No offense, but it was a real mess since some devices (mainly on android) don't register at no reason sometimes and the total app reliability cannot be assured. The worst part is you won't realize that you are in a middle of such a mess after publishing your app to the market!

Hence, despite being so heartbroken, I switched my push provider to a more reliable more feature-rich service named "OneSignal". Their phonegap/cordova plugins are commercially produced by their own dev team (not like parse that good guys do it for the good of community), so it is commercially supported, well documented for FREE (for apps sending less than 10M pushes per Month!!). 
their support rocks. I bet you say the same thing after setting up you app.

I have setup my app with their service and have used their compat plugin for phonegap 3.7 (I cannot update my phonegap for now). 
their plugin, supports showing buttons, push images and so much more that you won't see in parse. Also, their server rest api helps you to almost do anything with a simple rest client like fiddler. you can even track your pushes with their API.

I really, meant not to advertise their service here, but since @ropilz  and other good guys's main intention here was to help the community to suffer less, I thought this might be a good approach to do the same and save you so many bad days, nightmares and customer's insults.... 

have fun.

**Comment by skhouseholder** [comment]
Here's what worked for me (after lots of reading the instructions from https://github.com/taivo/parse-push-plugin and the SO link @goneale posted). It was a little confusing at first, so I'll explain here in hopes of helping someone:
1. In /platforms/android/src/&lt;your&gt;/&lt;package&gt;/&lt;name&gt;, create a file called MainApplication.java. Put this in it:
   
   ```
   package <your>.<package>.<name>;
   
   import android.app.Application;
   import com.parse.Parse;
   import com.parse.ParseInstallation;
   
   public class MainApplication extends Application {
       @Override
       public void onCreate() {
           super.onCreate();
           Parse.initialize(this, "YOUR_PARSE_APPID", "YOUR_PARSE_CLIENT_KEY");
           ParseInstallation.getCurrentInstallation().saveInBackground();
       }
   }
   ```
2. Go to the platforms/android/AndroidManifest.xml and add the attribute `android:name="MainApplication"` to the <application> tag. 
3. Remove the initialization code from your js. That initialization is taken care of in the java code you just wrote. Here's what's in my js now:
   
   ```
   function doParseSetupStuff() {
   
   parsePlugin.subscribe('SampleChannel', function() {
   
       parsePlugin.getInstallationId(function(id) {
   
           /**
            * Now you can construct an object and save it to your own services, or Parse, and correlate users to parse installations
            *
            var install_data = {
               installation_id: id,
               channels: ['SampleChannel']
            }
            *
            */
            appData.parseInstallation_id = id;
            appData.parseChannels = ['SampleChannel'];
            save();
   
       }, function(e) {
           alert('error');
       });
   });
   
   parsePlugin.registerCallback('onNotification', function() {
   
     window.onNotification = function(pnObj) {
       alert('We received this push notification: ' + JSON.stringify(pnObj));
       if (pnObj.receivedInForeground === false) {
           // TODO: route the user to the uri in pnObj
       }
     };
   
   }, function(error) {
     console.error(error);
   });
   };
   ```

That's it. Save them and run. Now my app doesn't crash when I tap on a notif.

Note: Since these instructions originated with a different plugin that has a different API, I was briefly concerned that the imports and calls to Parse and initialize() would be wrong since they don't match the syntax and calls in _this_ plugin. But that's not an issue because this is referencing methods in the Parse java files, not the plugin's API.
